import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
function RootLayout({ children }) {
  return (
    <html>
       <body>
      <header>this is header</header>
     {children}
      <footer>this is footer</footer>
      </body>
    </html>
  );
}

export default RootLayout;
